disabled_rules:
  # Проверка на большие тьюплс
  - large_tuple
  # Проверка длины строки
  - line_length
  # Проверка наличия комментариев
  - missing_docs
  # Проверка именования, включая имена переменных и функций
  - identifier_name
  # Проверка наличия пустых строк в конце файла
  - trailing_newline
  # Проверка наличия пробелов перед фигурными скобками в блоках
  - leading_whitespace
  # Проверка использования модификаторов доступа для свойств и функций
  - explicit_acl
  # Проверка на двойные closure
  - multiple_closures_with_trailing_closure
